version: '2'

services:
 db:
  image: microsoft/mssql-server-windows-express
  volumes:
   - .\docker\databases:C:\Data 
  environment:
   ACCEPT_EULA: Y
   sa_password: Docker+Sitecore!
   attach_dbs: "[{'dbName':'Sitecore_Core','dbFiles':['C:\\\\Data\\\\Sitecore.Core.mdf','C:\\\\Data\\\\Sitecore.Core.ldf']},{'dbName':'Sitecore_Master','dbFiles':['C:\\\\Data\\\\Sitecore.Master.mdf', 'C:\\\\Data\\\\Sitecore.Master.ldf']},{'dbName': 'Sitecore_Web', 'dbFiles': ['C:\\\\Data\\\\Sitecore.Web.mdf','C:\\\\Data\\\\Sitecore.Web.ldf']},{'dbName':'Sitecore_Analytics','dbFiles':['C:\\\\Data\\\\Sitecore.Analytics.mdf','C:\\\\Data\\\\Sitecore.Analytics.ldf']}]"   
  mem_limit: 1024m

 web:
  build: .\docker\web
  volumes:
   - .\src\WebApp:C:\Workspace
   - .\docker\serialization:C:\Sitecore\Data\serialization
  links: 
   - db
  environment:
   sa_password: Docker+Sitecore!
   sql_server: db
  mem_limit: 1024m

networks:
 default:
  external:
   name: "nat"